name: Run PowerShell Script

on:
  workflow_dispatch: # This triggers the workflow manually

jobs:
  run-powershell-script:
    runs-on: windows-latest  # Using a Windows runner

    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"
      
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the code in the repository

      - name: Run PowerShell script
        shell: pwsh
        run: |
          .\downloader.ps1

      - name: Run PowerShell script 2
        shell: pwsh
        run: |
          .\compress.ps1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.run_number }}
          release_name: updatedb.zip ${{ steps.date.outputs.date }}
          body: |
            Uploaded on ${{ steps.date.outputs.date }}
        
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          file: "*.zip"
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
